### PR TITLE
DgmlExport should respect the --nonsystem flag

### PR DESCRIPTION
**Pull request by yitzhaks**
Currently only the ConsoleVisualizer respects the --nonsystem flag.
Add support for for the flag to DgmlExport too.

### CODE REVIEW

**Comment by yitzhaks** [comment]
Looks like AppVeyor needs to upgrade to a new C# compiler.
@mikehadlow, should I revert to old C# or will you update AppVeyor?

**Comment by yitzhaks** [comment]
I was able to add a commit to get AppVeyor to use the latest and greatest C# compiler.

**Comment by mikehadlow** [comment]
Hi Yitzhak,
Thanks for more excellent work. Very nicely done. And I'm sorry I've taken a day to get around to looking at it. Also thanks for updating the AppVeyor image!
Mike.

**Comment by yitzhaks** [comment]
Thanks! I was waiting for this PR to be approved before I submitted the next, so as to avoid merge conflicts.

**Pull request merged**
