### PR TITLE
Splitted up into new project, where commandline operations are available

### PR DESCRIPTION
**Pull request by michaelthyregod**
As discussed I've created a PR to be able to use the core parts of the Assembly view classes in more general scenarios. I also did IlMerge to the commandline project, so it produces 1 single asmspy.exe file. The generation of the choco package should also work as expected with the new stuff.

Hope you can use it - next step would be to upload the nuget package from the AsmSpy project to nuget.org making it possible to include the basic libraries in other projects :-)

### CODE REVIEW

**Comment by michaelthyregod** [comment]
Seems like Appveyor does not pick up latest changes in the yml file - but I did change these, so it should work when merge are done.

**Comment by mikehadlow** [comment]
AppVeyor build has failed. Maybe @rahulpnath can help?

**Comment by mikehadlow** [comment]
AppVeyor failing on master too: https://ci.appveyor.com/project/rahulpnath/asmspy/branch/master

**Comment by michaelthyregod** [comment]
It's not picking the https://github.com/mikehadlow/AsmSpy/blob/master/appveyor.yml from here - seems like it's using an old one?

**Comment by mikehadlow** [comment]
Maybe @rahulpnath can help??

**Comment by michaelthyregod** [comment]
Seems like it's static with the yml file - and not picking up the one from the branch - so he might have to change that yes. Apart from that I can see all looks like it's building as expected.

**Comment by rahulpnath** [comment]
Yes currently it ignores the yml in source and uses the one specified in
appveyor. I have updated the setting to use the branch yml file and
triggered a rebuild. It's passing now!

Rahul
http://rahulpnath.com

On Jan 17, 2017 8:43 PM, "Michael Thyregod" <notifications@github.com>
wrote:

Seems like it's static with the yml file - and not picking up the one from
the branch - so he might have to change that yes. Apart from that I can see
all looks like it's building as expected.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mikehadlow/AsmSpy/pull/35#issuecomment-273067668>, or mute
the thread

**Comment by michaelthyregod** [comment]
@rahulpnath @mikehadlow - I don't know how you push to choco repository today? Manual or triggered by AppVeyor? If it's manual, we can add the additional nuget package for nuget.org - but someone should upload it then, and I suggest that it's the owner of the package. If it's triggered we can do something there as well. Let me know and I will gladly help making it work - both would require some modifications to AppVeyor settings - and I would even recommend to do it with automated triggers that reads from the YML file - as far as I remember AppVeyor can be setup to only push to nuget and choco if it's a build from master, ensuring that it will never upload if it's a pull-request. Let me know what you think.

**Comment by michaelthyregod** [comment]
You can add me as a member of your AppVeyor Team and then add me to the AsmSpy project, so I can play a little around with the configuration for getting the artifacts to assemble - I can see that the last build did not produce artifact for the chocolatey package, because the APPVEYOR_REPO_TAG_NAME was not set.

**Comment by mikehadlow** [comment]
@michaelthyregod. I've added you as a collaborator to the AsmSpy GitHub project. @rahulpnath, can you also add @michaelthyregod to the AppVeyor team. Many thanks!

**Comment by rahulpnath** [comment]
@mikehadlow Happy to do that.
@michaelthyregod Can you send me your email to add you? Yes, Appveyor is set to create a deployment package only on master and on a tagged commit. A tag to confirm that we intend to release. So if you tag the commit with the release number and push, it will trigger a new build and create a deployment package.

More details on the build here https://github.com/mikehadlow/AsmSpy/pull/23

**Comment by michaelthyregod** [comment]
@rahulpnath - You should be able to add me by my GitHub name "michaelthyregod" - if not my mail is "michael_thyregod@hotmail.com"

**Comment by rahulpnath** [comment]
@michaelthyregod I have added you in. Let me know if that works

**Comment by michaelthyregod** [comment]
@rahulpnath - I still can't see the stuff on Appveyor.

**Comment by michaelthyregod** [comment]
@mikehadlow @rahulpnath - is the intention that the build should only generate the choco package if the tag is set, and version is in the tag as well? Right now I can't see how it generates new choco package and pushes it?

**Comment by rahulpnath** [comment]
@michaelthyregod  Yes have kept it to release to chocolatey only when a tag is set and pushed up. Since we might not want to deploy every time we create a build. More details on this https://github.com/mikehadlow/AsmSpy/pull/23. Happy to change this though if you think otherwise. 

Hope you are all setup on Appveyor. Let know if you need further help with this

**Comment by michaelthyregod** [comment]
@rahulpnath - Yes I can access the AppVeyor account - just had to log in again :-) I've also already did a build up there, and it can also push to Chocolatey as well.

**Pull request merged**
