### PR TITLE
Added chocolatey package nuspec and install scripts

### PR DESCRIPTION
**Pull request by rahulpnath**
Added in the nuspec file for chocolatey for fixing #14 . Feel free to add/edit the values as you feel.

Once you merge in you will have to create the package and push it to your [Chocolatey](https://chocolatey.org/packages/upload) account.
- Running [cpack](https://github.com/chocolatey/choco/wiki/CommandsPack) from the chocolatey folder will create the package
- Use [cpush](https://github.com/chocolatey/choco/wiki/CommandsPush) or the web UI to upload the package

***If you are regenerating the zip package, you might have to update the sha1 checksum value.***
 I used the certutil to generate it (just in case you needed it) *CertUtil -hashfile AsmSpy.zip sha1*

### CODE REVIEW

**Comment by mikehadlow** [comment]
Thanks for this. Great work. Would you be interested in maintaining the chocolatey package/account?

**Comment by rahulpnath** [comment]
Sure I don't mind. Between its a really useful tool!

**Comment by mikehadlow** [comment]
That would be great. Many thanks Rahul!

**Comment by rahulpnath** [comment]
Sure no worries, would be helpful if you can add as a moderator to the repository, so I can see if I can trigger off an automated build

**Comment by mikehadlow** [comment]
Added you as a collaborator.

**Pull request merged**
