### PR TITLE
Packaging and rename of core project

### PR DESCRIPTION
**Pull request by michaelthyregod**
I had to rename the core project to be able to still produce the existing choco package called "asmspy", which was conflicting with the name of the nuget package which also was "asmspy" - so now the core is called asmspy.core and produces a nuget package called "nuget.core" which can be deployed to nuget.org

Also reworked the AppVeyor.yml file a bit, so it now produces the 3 artifacts with version (please review that), and makes it possible to use existing environment to push to Chocolatey. Now we just ned an environment for pushing to nuget.org as well.

### CODE REVIEW

**Comment by mikehadlow** [comment]
Thanks for keeping on at this Michael! Excellent work.

**Comment by mikehadlow** [comment]
I'm very happy for you to setup the NuGet project too. So long as you're happy to take responsibility for the AsmSpy.Core package. Let me know if you need anything.

**Comment by michaelthyregod** [comment]
As it is right now I can see the chocolatey environment (account) in AppVeyor is owned by @rahulpnath - so I don't know if he's the one that should own the nuget environment (nuget account) as well, since the Appveyor account is owned by him as well? Let me know what you think? The only thing I need is just that the AppVeyor build also has an environment that can push to nuget.org, then it should be pretty easy.

BTW - can we already make a release now, or should we wait until the nuget.org account is there as well?

**Comment by mikehadlow** [comment]
Make a release now if you want. Let's ask @rahulpnath if he would like to
won the NuGet account too.

On Thu, Jan 26, 2017 at 11:58 AM, Michael Thyregod <notifications@github.com

**Comment by michaelthyregod** [comment]
I will just update the documentation then with the new -rsw (referencedstartswith) switch for the asmspy.exe. Then I can do a release if you don't have any objections.

**Comment by mikehadlow** [comment]
Sounds good.

On Thu, Jan 26, 2017 at 12:14 PM, Michael Thyregod <notifications@github.com

**Comment by michaelthyregod** [comment]
I've pushed the package to choco, and it should be there as soon as it gets approved by moderator [https://chocolatey.org/packages/asmspy/1.3.71](https://chocolatey.org/packages/asmspy/1.3.71)

**Comment by rahulpnath** [comment]
Sorry guys I am on vacation with limited access. Will get to this Monday morning (Sydney time). @michaelthyregod Can you let know if you are now able to access appveyor?

**Comment by rahulpnath** [comment]
I have set up the Nuget account and pushed the packages. I have setup an environment in appveyor for the same. 
https://www.nuget.org/packages/AsmSpy.Core/
https://www.nuget.org/packages/asmspy/

@michaelthyregod  Can you pass me your nuget account username? Tried looking you up but could not find. 
@mikehadlow I have added you as an owner.

I have updated the appveyor config file for this https://github.com/mikehadlow/AsmSpy/pull/38. 

Let know if all looks fine.

**Pull request merged**
