### PR TITLE
Add support for excluding assemblies and honor alternative found versions

### LINKED ISSUE #71: Not StrongNamed assemblies reported as error on version mismatch
Hi,

this time before sending any code changes I wanted to discuss the situation and get a clear view.

When an assembly is not StrongNamed and exists in another version than is requested by another assembly, the assembly is still loaded in .NET.
`assemblyBindings` do not apply, as this is only available for strong named assemblies.

So, while a project might actually have problems running (because of incompatible version combinations), from a assembly loading perspective, everything is "fine".

End of last year there was the following commit: https://github.com/mikehadlow/AsmSpy/commit/f60398a78edea988ccee8a8459c2a492537e04bf

While the main intention of the commit was to introduce a ConsoleTreeVisualizer it also contains changes for `AlternativeFoundVersion`. These alternative versions are actually reported as warnings while the assemblies are "searched". However later on in the process, the normal `ConsoleVisualizer` doesn't care about those version mismatches and just reports a missing assembly.

So long story short: I think, AsmSpy should actually only report warnings for version mismatches (if we are not talking StrongNamed assemblies).
However this would be kind of a breaking change to the current implementation?

My recommandations would be:
* Stick to how .NET actually loads assemblies and therefor do not error out on those version mismatches
* Make sure that all visualizers follow a similar implementation (Console vs ConsoleTree)
* Optional: If need be, add a small switch to toggle how version mismatches for non StrongNamed assemblies are handled

Regards,
Philipp

### PR DESCRIPTION
**Pull request by pfeigl**
This changeset basically does a few things (and I should have split it up a little better, but also didn't want to spam multiple PRs).

* Adds support to exclude assemblies from the process. As with the existing `rsw` option, this is tested via a simple "StartsWith". It is possible to provide multiple `--exclude`'s
* Honor `AlternativeVersions` in the `ConsoleVisualizer`. See the following picture:
image
* Started with a very basic refactoring in the sense of at least moving all the visualizers into their own folders

This fixes #71 mostly. 
Mostly, because I only fixed the ConsoleVisualizer and not any of the others - but I'm simply out of time to provide more support for this feature right now - sorry.

// p.s. I fixed quite a few inconsistent CLRFs in a few files. For a better "review" of the actual changes, append &w=1 to the github URL, which will ignore all the whitespace changes.

### CODE REVIEW

**Comment by mikehadlow** [comment]
Thanks for a great job Philipp. Something's failing with the appveyor checks, so I'll have to spare some time to look at that, but hope to review and merge in the next day or so.
I really appreciate all the work you've put into AsmSpy.
Mike

**Comment by pfeigl** [comment]
Uh, the unit test failures were actually caused by me. Pushed a small fix for it, let's see what the build status says.

**Comment by mikehadlow** [comment]
Merged. Thanks for fixing the tests Philipp.
Once again sorry for taking far too long to get around to this :(

**Comment by pfeigl** [comment]
No worries Mike, it also took me quite some time to provide the mentioned changes. Also we just used a "self-compiled" version for as long as the new release was not available.

**Pull request merged**
